# Generated by Django 4.2.30 on 2026-07-09 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphrag', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='processing_progress',
            field=models.IntegerField(default=0, help_text='Progress percentage (0-100)'),
        ),
        migrations.AddField(
            model_name='document',
            name='processing_step',
            field=models.CharField(blank=True, default='', help_text='Current processing step description', max_length=200),
        ),
    ]
