# Generated by Django 4.2.30 on 2026-07-10 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphrag', '0002_document_processing_progress_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='source',
            field=models.CharField(blank=True, default='', help_text='Optional source label (e.g. research-paper, internal-wiki)', max_length=255),
        ),
    ]
