# Generated by Django 4.2.30 on 2026-07-13 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphrag', '0003_document_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='querylog',
            name='retrieval_mode',
            field=models.CharField(choices=[('GRAPH', 'Graph Only'), ('VECTOR', 'Vector Only'), ('HYBRID', 'Hybrid'), ('MULTIHOP', 'Multi-Hop')], default='HYBRID', max_length=20),
        ),
    ]
