# Generated by Django 4.2.30 on 2026-07-15 04:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('graphrag', '0004_alter_querylog_retrieval_mode'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoiceChatSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_id', models.UUIDField(help_text='Unique session UUID generated by frontend', unique=True)),
                ('title', models.CharField(default='Voice Chat', max_length=255)),
                ('doc_id', models.CharField(max_length=100)),
                ('doc_name', models.CharField(max_length=255)),
                ('messages', models.JSONField(default=list, help_text='List of message objects (role, content, timestamp, citedNodes)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voice_chat_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
