# Generated by Django 4.2.30 on 2026-07-15 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphrag', '0005_voicechatsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='summary',
            field=models.TextField(blank=True, default='', help_text='Auto-generated 100-word document summary'),
        ),
    ]
